# Generated by Django 4.0.3 on 2022-03-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='describtion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
