# Generated by Django 4.0.3 on 2022-03-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Published Video', 'verbose_name_plural': 'Published Videos'},
        ),
    ]
