# Generated by Django 4.0.3 on 2022-03-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_delete_videoproxy_videopublishedproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft'), ('UN', 'Unlisted'), ('PR', 'Private')], default='DR', max_length=2),
        ),
    ]
