# Generated by Django 4.0.3 on 2022-03-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_published_timestamp_alter_video_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='published_timestamp',
            new_name='publish_timestamp',
        ),
    ]
